feat(clevercloud): add clevercloud secrets
octopize/avatar-deployment pull request #20
Opened 2023-06-08 11:13 UTC by ykatchou

I did add the clevercloud_sso_salt secrets across the deployment chain.
Related to https://github.com/octopize/avatar/pull/1368

2023-06-08 13:32 UTC, tcrasset requested changes
Very nice that you've thought about adding it in the helm template + docker-compose!

Small changes needed though!

2023-06-08 13:32 UTC, tcrasset commented on helm-chart/templates/api-secrets.yaml
> +  clevercloud_sso_sal: {{ .Values.api.clevercloudSsoSalt | b64enc | quote }}
```suggestion
  clevercloud_sso_salt: {{ .Values.api.clevercloudSsoSalt | b64enc | quote }}
```

2023-06-08 13:32 UTC, tcrasset commented on docker/docker-compose.yml
> +      - clevercloud_sso_salt
I don't think it's necessary to have it in the worker

2023-06-08 13:32 UTC, tcrasset commented on docker/Makefile
You have to add it in `secrets-with-username-auth` and `secrets-with-email-auth` too.

2023-09-21 09:11 UTC, ykatchou commented
Hello, i did take all your comments into account. I did also rebase.

2023-09-21 09:13 UTC, tcrasset approved these changes

2023-09-21 09:13 UTC, tcrasset commented on helm-chart/templates/_helpers.tpl
> +			- name: LOG_LEVEL
can you run  `make render-helm` (or `make lint`) to make sure the helm template works as you switched to tabs here? Makes me think that we should have a `make lint-fix`

2023-09-21 10:34 UTC, merged